// Veredito legal de embed — verificado em 2026-09-25 via fetch direto. Sem bypass, sem proxy, sem download.
export type LegalStatus = "embed" | "link-only" | "review" | "metadata-only";
export interface SourceVerdict {
  id:string; name:string; url:string; status:LegalStatus;
  reason:string; player?: "youtube"|"vimeo"|"archive-mp4"|"playlist"|"none";
  playlistId?:string; note?:string;
}
export const sourceVerdicts: SourceVerdict[] = [
  { id:"argflix", name:"Argflix — Cine Argentino Gratis Online", url:"https://www.argflix.com/", status:"review", reason:"Catálogo que organiza material que circula no YouTube e declara verificar obra completa e melhor qualidade. Não hospeda player próprio visível no HTML — embed deve ser feito no YouTube original de cada obra, verificando embedAllowed por vídeo. Não incorporar iframe do Argflix sem autorização.", player:"none", note:"Listar como fonte de curadoria + link. Embedar só o YouTube original de cada filme." },
  { id:"yt-cine-argentino-1", name:"YouTube Playlist — Cine Argentino. Películas Argentinas Completas", url:"https://www.youtube.com/playlist?list=PLj9stbUOTbCuRN8CqKn_t93L5MvhPf98U", status:"embed", reason:"Playlist pública YouTube — embed oficial videoseries permitido. Verificar embedAllowed por vídeo antes de publicar.", player:"playlist", playlistId:"PLj9stbUOTbCuRN8CqKn_t93L5MvhPf98U" },
  { id:"yt-cine-argentino-2", name:"YouTube Playlist — CINE ARGENTINO Películas Completas #changuitafilms", url:"https://www.youtube.com/playlist?list=PLtyBRTHqbPDcqRY1Yk7e0OLkvJtcw8rZX", status:"review", reason:"Playlist de terceiro (Changuita Films). Embed técnico permitido via videoseries, mas titularidade dos longas precisa de revisão editorial por obra (pode ser upload não-oficial). Publicar como review, não auto-publish.", player:"playlist", playlistId:"PLtyBRTHqbPDcqRY1Yk7e0OLkvJtcw8rZX" },
  { id:"acau", name:"ACAU — Agencia del Cine y Audiovisual del Uruguay (YouTube)", url:"https://www.youtube.com/@ACAUyoutube/playlists", status:"embed", reason:"Instituição pública oficial do Uruguai. Playlists e vídeos oficiais — embed permitido quando o vídeo permitir. Prioridade para cinema uruguaio.", player:"youtube" },
  { id:"uruguay-audiovisual", name:"Uruguay Audiovisual — Proyectos", url:"https://uruguayaudiovisual.com/en/proyectos/", status:"metadata-only", reason:"Catálogo de projetos (título, diretor, ano, status) com LOAD MORE, sem player. Usar como fonte de metadados + link para obra oficial. Não há o que embedar.", player:"none" },
  { id:"libreflix", name:"Libreflix — Cinema livre (CC)", url:"https://libreflix.org/", status:"embed", reason:"Plataforma open-source de obras com licenças livres (ex: Eskawata Kayawai Huni Kuin, A Educação Proibida, Linha de Montagem). Embedar com atribuição conforme licença de cada obra. Verificar licença por título.", player:"archive-mp4" },
  { id:"telabrasil", name:"Tela Brasil — Audiovisual Brasileiro Gratuito", url:"https://telabrasil.cultura.gov.br/", status:"review", reason:"Home retorna quase sem HTML server-side (app JS). Não foi possível verificar player/embed sem login. Tratar como review: listar como link, só embedar após verificação manual de embed permitido.", player:"none" },
  { id:"itau-play", name:"Itaú Cultural Play", url:"https://www.itauculturalplay.com.br/browser", status:"link-only", reason:"Todo o catálogo exige 'Fazer login' (visto no HTML: Travessias, Bienal, Helena Ignez, Macunaíma etc.). Incorporar sem login seria contornar controle de acesso. Só link 'Assistir na fonte original (requer login)'.", player:"none" },
  { id:"spcine", name:"Spcine Play", url:"https://www.spcineplay.com.br/", status:"link-only", reason:"Exige 'Entrar / Criar uma conta', Powered by EiTV CLOUD. Sem catálogo público verificável. Só link externo.", player:"none" },
  { id:"ubuplay", name:"Ubuplay", url:"https://www.ubuplay.com/app", status:"link-only", reason:"App JS com apenas cookie banner no HTML. Sem evidência de embed público. Só link externo até verificação manual.", player:"none" },
  { id:"archive", name:"Internet Archive — filmes latinos domínio público/CC", url:"https://archive.org/", status:"embed", reason:"MP4 direto oficial (ex: Rio 1940s travelogue) via download/archive. Usar Html5Provider com URL de download, preservando attribution.", player:"archive-mp4" },
  { id:"vimeo", name:"Vimeo — perfis oficiais", url:"https://vimeo.com/", status:"review", reason:"Só embedar com embed_allowed via oEmbed por vídeo. Sem ID verificado no momento — nenhum item Vimeo publicado até verificação.", player:"none" },
];
